import{a as m,S as y,i as l}from"./assets/vendor-a94593f8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();class b{constructor(){this.searchQuery="",this.page=1,this.PER_PAGE=40}async fetchGallery(){const t={method:"get",url:"https://pixabay.com/api/",params:{key:"34523545-f21683fd59bfc3e4e2549fe07",q:`${this.searchQuery}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:`${this.page}`,per_page:`${this.PER_PAGE}`}};try{const i=(await m(t)).data;return this.incrementPage(),i}catch(s){console.error(s)}}incrementPage(){this.page+=1}resetPage(){this.page=1}resetEndOfHits(){this.endOfHits=!1}get query(){return this.searchQuery}set query(t){this.searchQuery=t}}let w=new y(".photo-card a",{captions:!0,captionsData:"alt",captionDelay:250});const P=document.querySelector(".search-form"),d=document.querySelector(".gallery"),u=document.querySelector(".loader");function f(o,t){o.classList.toggle("is-hidden",!t)}let a=0;const c=new b;P.addEventListener("submit",L);function L(o){if(o.preventDefault(),d.innerHTML="",c.query=o.currentTarget.elements.searchQuery.value.trim(),c.resetPage(),c.query===""){l.warning({title:"Warning",message:"Please, fill the main field",position:"topRight",color:"yellow"});return}o.currentTarget.reset(),a=0,h()}async function h(){f(u,!0);const o=await c.fetchGallery(),{hits:t,total:s}=o;if(a+=t.length,!t.length){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight",color:"red"});return}E(t),a+=t.length,a<s&&l.success({title:"Success",message:`Hooray! We found ${s} images !!!`,position:"topRight",color:"green"}),a>=s&&l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue"}),f(u,!1)}function E(o){const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:n,comments:p,downloads:g})=>`
       <div class="photo-card">
       <a href="${i}">
       <img class="photo-img" src="${s}" alt="${e}" loading="lazy" />
       </a>
       <div class="info">
       <p class="info-item"><b>Likes</b>${r}</p>
       <p class="info-item"><b>Views</b>${n}</p>
       <p class="info-item"><b>Comments</b>${p}</p>
       <p class="info-item"><b>Downloads</b>${g}</p>
       </div>
       </div>`).join("");d.insertAdjacentHTML("beforeend",t),w.refresh()}function S(){c.incrementPage(),h()}function $(){return window.innerHeight+window.scrollY>=document.documentElement.scrollHeight}function q(){$()&&S()}window.addEventListener("scroll",q);
//# sourceMappingURL=commonHelpers.js.map
