import{a as y,S as b,i as l}from"./assets/vendor-a94593f8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();class L{constructor(){this.searchQuery="",this.page=1,this.PER_PAGE=40}async fetchGallery(){const t={method:"get",url:"https://pixabay.com/api/",params:{key:"34523545-f21683fd59bfc3e4e2549fe07",q:`${this.searchQuery}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:`${this.page}`,per_page:`${this.PER_PAGE}`}};try{const i=(await y(t)).data;return this.incrementPage(),i}catch(s){console.error(s)}}incrementPage(){this.page+=1}resetPage(){this.page=1}resetEndOfHits(){this.endOfHits=!1}get query(){return this.searchQuery}set query(t){this.searchQuery=t}}let P=new b(".photo-card a",{captions:!0,captionsData:"alt",captionDelay:250});const v=document.querySelector(".search-form"),d=document.querySelector(".gallery"),u=document.querySelector(".load-more");let a=0;const c=new L;v.addEventListener("submit",S);u.addEventListener("click",h);const w={rootMargin:"50px",root:null,threshold:.3};new IntersectionObserver(h,w);function S(o){if(o.preventDefault(),d.innerHTML="",c.query=o.currentTarget.elements.searchQuery.value.trim(),c.resetPage(),c.query===""){l.warning({title:"Warning",message:"Please, fill the main field",position:"topRight",color:"yellow"});return}a=0,p(),f(hits)}function h(){c.incrementPage(),p()}async function p(){u.classList.add("is-hidden");const o=await c.fetchGallery(),{hits:t,total:s}=o;if(a+=t.length,!t.length){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight",color:"red"}),u.classList.add("is-hidden");return}f(t),a+=t.length,a<s&&(l.success({title:"Success",message:`Hooray! We found ${s} images !!!`,position:"topRight",color:"green"}),u.classList.remove("is-hidden")),a>=s&&l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue"})}function f(o){const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:n,comments:m,downloads:g})=>`
       <div class="photo-card">
       <a href="${i}">
       <img class="photo-img" src="${s}" alt="${e}" loading="lazy" />
       </a>
       <div class="info">
       <p class="info-item"><b>Likes</b>${r}</p>
       <p class="info-item"><b>Views</b>${n}</p>
       <p class "info-item"><b>Comments</b>${m}</p>
       <p class="info-item"><b>Downloads</b>${g}</p>
       </div>
       </div>`).join("");d.insertAdjacentHTML("beforeend",t),P.refresh()}
//# sourceMappingURL=commonHelpers.js.map
